name: Publish Docker image (GHCR)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  IMAGE_NAME: pokemon-dashboard

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  # necesario para publicar en GHCR
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME:latest
            ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME:${{ github.sha }}
